language: node_js
node_js:
- '4.5'
- '5.10'
- '6'
- '8'
- stable
sudo: false
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
cache:
  directories:
  - node_modules
